Parameters:
  RdsUsername:
    Type: String
    NoEcho: true
    MinLength: 1
    Default: postgres
  RdsPassword:
    Type: String
    NoEcho: true
    MinLength: 24
    Default: 5bcfd3fb5cba35da5f1be3c347bc
  DataBucketName:
    Description: Bucket name where data is persisted
    Type: String
    MinLength: 1
Resources:
  EksServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: hindsight-service-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEKSServicePolicy'
        - 'arn:aws:iam::aws:policy/AmazonEKSClusterPolicy'
  EksUserRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: "/"
      RoleName: hindsight-user-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Join
                - ""
                - - "arn:aws:iam::"
                  - !Ref "AWS::AccountId"
                  - ":root"
            Action: "sts:AssumeRole"
  EksCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: hindsight-kubernetes
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref EksControlPlaneSg
        SubnetIds:
          - !Ref VpcSubnet1
          - !Ref VpcSubnet2
      RoleArn: !GetAtt
        - EksServiceRole
        - Arn
      Version: 1.14
  EksWorkerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: hindsight-worker-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy'
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly'
        - 'arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
  EksWorkerGroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: hindsight-kubernetes
      InstanceTypes:
        - t2.large
      NodegroupName: hindsight-worker-group
      NodeRole: !GetAtt
        - EksWorkerRole
        - Arn
      ScalingConfig:
        DesiredSize: 4
        MinSize: 3
        MaxSize: 7
      Subnets:
        - !Ref VpcSubnet1
        - !Ref VpcSubnet2
    DependsOn: EksCluster
  VpcRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: Public Subnets
        - Key: Network
          Value: Public
  VpcGatewayRoute:
    DependsOn: VpcGatewayAttachment
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref VpcRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref VpcGateway
  VpcSubnet1Rta:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref VpcSubnet1
      RouteTableId: !Ref VpcRouteTable
  VpcSubnet2Rta:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref VpcSubnet2
      RouteTableId: !Ref VpcRouteTable
  EksControlPlaneSg:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: hindsight-control-plane-sg
      GroupDescription: Cluster communication with worker nodes
      VpcId: !Ref Vpc
  Vpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
  VpcSg:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: hindsight-vpc-sg
      GroupDescription: VPCSecured
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
  VpcSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: us-east-2a
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref Vpc
  VpcSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: us-east-2b
      CidrBlock: 10.0.8.0/24
      VpcId: !Ref Vpc
  VpcGateway:
    Type: 'AWS::EC2::InternetGateway'
  VpcGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref VpcGateway
      VpcId: !Ref Vpc
  PostgresInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 100
      BackupRetentionPeriod: 7
      DBInstanceClass: db.t3.medium
      DBName: metastore
      Engine: postgres
      EngineVersion: 10
      MultiAZ: 'true'
      StorageEncrypted: 'true'
      DBSubnetGroupName: !Ref PostgresSubnetGroup
      DBParameterGroupName: !Ref PostgresParameterGroup
      VPCSecurityGroups:
        - !Ref VpcSg
      MasterUsername: !Ref RdsUsername
      MasterUserPassword: !Ref RdsPassword
      Port: 5432
      PubliclyAccessible: false
      StorageType: gp2
  PostgresSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: PostgresSubnet
      SubnetIds:
        - !Ref VpcSubnet1
        - !Ref VpcSubnet2
  PostgresParameterGroup:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: Encrypt RDS connections
      Family: postgres10
      Parameters:
        rds.force_ssl: true
  DataBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Ref DataBucketName
  DataBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref DataBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:DeleteObject'
              - 's3:DeleteObjectVersion'
              - 's3:GetObject'
              - 's3:GetObjectVersion'
              - 's3:PutObject'
              - 's3:ListBucket'
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt
                  - EksWorkerRole
                  - Arn
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref DataBucket
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref DataBucket
                  - /*
  # ViewStateRedis:
  #   Type: 'AWS::ElastiCache::CacheCluster'
  #   Properties:
  #     CacheNodeType: cache.t3.small
  #     CacheSubnetGroupName: !Ref ViewStateRedisSubnetGroup
  #     Engine: redis
  #     EngineVersion: 5.0.4
  #     NumCacheNodes: 1
  #     Port: 6379
  #     PreferredAvailabilityZone: us-east-2a
  #     VpcSecurityGroupIds:
  #       - !Ref VpcSg
  # ViewStateRedisSubnetGroup:
  #   Type: 'AWS::ElastiCache::SubnetGroup'
  #   Properties:
  #     CacheSubnetGroupName: ViewStateRedisSubnetGroup
  #     SubnetIds:
  #       - !Ref VpcSubnet1
  #       - !Ref VpcSubnet2
Outputs:
  Postgres:
    Description: Postgres instance address
    Value: !GetAtt PostgresInstance.Endpoint.Address
  NodeRole:
    Description: EKS Worker Node Role ARN
    Value: !GetAtt EksWorkerRole.Arn
  UserRole:
    Description: EKS User Role ARN
    Value: !GetAtt EksUserRole.Arn
